version: "3.8"
services:
  nominatim:
    image: "mediagis/nominatim:4.5"
    container_name: nominatim
    environment:
      - "PBF_PATH=/nominatim/data/osm-map.pbf"
    ports:
      - "5173:8080"
    volumes:
      - "./osm-data:/nominatim/data"
    networks:
      - osm_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

  osrm_extract:
    image: osrm/osrm-backend
    container_name: osrm_extract
    command: "osrm-extract -p /opt/car.lua /data/osm-map.pbf"
    volumes:
      - "./osm-data:/data"
    networks:
      - osm_network
    restart: "no"

  osrm_partition:
    image: osrm/osrm-backend
    container_name: osrm_partition
    command: "osrm-partition /data/osm-map.osrm"
    volumes:
      - "./osm-data:/data"
    networks:
      - osm_network
    depends_on:
      - osrm_extract
    restart: "no"

  osrm_customize:
    image: osrm/osrm-backend
    container_name: osrm_customize
    command: "osrm-customize /data/osm-map.osrm"
    volumes:
      - "./osm-data:/data"
    networks:
      - osm_network
    depends_on:
      - osrm_partition
    restart: "no"

  osrm_routed:
    image: osrm/osrm-backend
    container_name: osrm_routed
    command: "osrm-routed --algorithm mld /data/osm-map.osrm"
    ports:
      - "5000:5000"
    volumes:
      - "./osm-data:/data"
    networks:
      - osm_network
    depends_on:
      - osrm_customize
    restart: always

networks:
  osm_network:
    driver: bridge
